### ISSUE TITLE
ifplugd error while updating pwnix 

### ISSUE THREAD

**Issue by yoy123** [aopp/android_kernel_lge_hammerhead#13]
[update.log](https://github.com/aopp/android_kernel_lge_hammerhead/files/1595551/update.log)

**Comment by yoy123** [comment]
chef-staktrace.out

Chef::Exceptions::Service: service[ifplugd] (pwnix_base_cookbook::kali_services line 21) had an error: Chef::Exceptions::Service: /usr/sbin/update-rc.d -n -f ifplugd failed - #<Process::Status: pid 8157 exit 1>
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:240:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:321:in `block in run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:320:in `each'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:320:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/provider.rb:154:in `process_resource_requirements'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/provider.rb:133:in `run_action'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource.rb:622:in `run_action'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:69:in `run_action'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:97:in `each'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:97:in `block in converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:96:in `converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:715:in `block in converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:710:in `catch'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:710:in `converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:749:in `converge_and_save'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:286:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:295:in `block in fork_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:283:in `fork'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:283:in `fork_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:248:in `block in run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:236:in `run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:450:in `loop'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:434:in `run_application'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:59:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/solo.rb:226:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/bin/chef-solo:25:in `<top (required)>'
/usr/local/bin/chef-solo:22:in `load'
/usr/local/bin/chef-solo:22:in `<main>'

>>>> Caused by Chef::Exceptions::Service: /usr/sbin/update-rc.d -n -f ifplugd failed - #<Process::Status: pid 8157 exit 1>
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:240:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:321:in `block in run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:320:in `each'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/mixin/why_run.rb:320:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/provider.rb:154:in `process_resource_requirements'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/provider.rb:133:in `run_action'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource.rb:622:in `run_action'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:69:in `run_action'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:97:in `each'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:97:in `block in converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/runner.rb:96:in `converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:715:in `block in converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:710:in `catch'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:710:in `converge'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:749:in `converge_and_save'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/client.rb:286:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:295:in `block in fork_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:283:in `fork'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:283:in `fork_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:248:in `block in run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:236:in `run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:450:in `loop'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/client.rb:434:in `run_application'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application.rb:59:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/lib/chef/application/solo.rb:226:in `run'
/var/lib/gems/2.3.0/gems/chef-12.21.4/bin/chef-solo:25:in `<top (required)>'
/usr/local/bin/chef-solo:22:in `load'
/usr/local/bin/chef-solo:22:in `<main>'
